version: "3"
services:
  api:
    image: autograde_api:latest
    container_name: autograde_api_container
    restart: unless-stopped
    build:
      context: ./autograde_api
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./dictionaries:/autograde_api/dictionaries
      - ./models:/autograde_api/models
      - ./config.yaml:/autograde_api/config.yaml
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - net
  bot:
    image: autograde_bot:latest
    container_name: autograde_bot_container
    restart: unless-stopped
    build:
      context: ./EGE-Writing-Autograde-Bot
      dockerfile: ./Dockerfile
    env_file:
      - ./EGE-Writing-Autograde-Bot/.env
    networks:
      - net
  web:
    image: autograde_web:latest
    container_name: autograde_web_container
    restart: unless-stopped
    build:
      context: ./Streamlit-for-autograde-eng-letter
      dockerfile: ./Dockerfile
    env_file:
      - ./Streamlit-for-autograde-eng-letter/.env
    ports:
      - 8501:8501
    expose:
      - 8501
    networks:
      - net
networks:
  net:
